function isfull = isFullPath(mypath)

% isfull = isFullPath(mypath) decides if mypath is full 

isfull = ~isempty(regexp(mypath,'Users/lucas', 'once')) | ...
         ~isempty(regexp(mypath,'Volumes', 'once'))     | ...
         ~isempty(regexp(mypath,'jukebox', 'once'))     | ...
         ~isempty(regexp(mypath,'C:', 'once'))          | ...
         ~isempty(regexp(mypath,'D:', 'once'))          | ...
         ~isempty(regexp(mypath,'bucket', 'once'))      | ...
         numel(strfind(mypath,'/')) > 3                 | ...
         numel(strfind(mypath,'\')) > 3                   ...
         ;
