function fh = plotAvgDff(avgDff,mazeID,trialtype,fh,saveFlag,ROIoutline)

% fh = plotAvgDff(avgDff,mazeID,trialtype,fh)
% plots average dff by trial epoch
% avgDff: data structure generated by avgDffByTrialEpoch.m (required)
% mazeID: picks most advanced maze in session by default
% trialtype: see avgDff.trialTypeList for options, defailt 'correctL'
% fh: figure handle, both for input and output
% LP jul 2016

% defaults / load variables
defaults={[];[];'correctL';[];true;[]};
inputnames = {'avgDff';'mazeID';'trialtype';'fh';'saveFlag';'ROIoutline'};
if nargin < numel(defaults)
  for i = nargin+1:length(defaults)
    temp=defaults{i};
    eval([inputnames{i} '=temp;']);
  end
end

if isempty(mazeID)
  mazeID = max(avgDff.mazeList);
end
if isempty(fh)
  fh = figure;
end

thisavg = eval(sprintf('avgDff.maze(%d).%s',find(avgDff.mazeList == mazeID),trialtype));

% first put everyone on the same scale
alldff = [];
for ii = 2:length(avgDff.epochList)
  alldff = cat(3,alldff,eval(sprintf('thisavg.%s.avg',avgDff.epochList{ii})));
end
absmax = prctile(abs(alldff(:)),95);
cl     = [-absmax absmax];

cmap      = colormap(parula);
cmap(1,:) = [0 0 0]; % nans should be black

%%
figure(fh);
set(fh,'position',[5 130 935 575],'color',[0 0 0])

for ii = 2:numel(avgDff.epochList)
  subplot(2,3,ii-1)
  imagesc(alldff(:,:,ii-1),cl); colormap(cmap)
  axis image; axis off
  ah = gca; if ~isempty(ROIoutline); drawROI(ROIoutline,'w',ah); end
  title([trialtype ' ' avgDff.epochList{ii}],'color','w','fontsize',15)
  %     if ii == length(avgDff.epochList); colorbar('location','southoutside','color','w'); end
end

figure; imagesc([],cl)
set(gcf,'color','k')
colorbar('location','southoutside','color','w');

if saveFlag
  fn = sprintf('dffAvg_mz%d_%s',mazeID,trialtype);
  saveas(fh,fn);
end